// src/i18n/index.js
// ─────────────────────────────────────────────────────────────
//  COMPLETE SYSTEM-WIDE i18n
//  Usage anywhere:
//    import { useTranslation } from '../i18n';
//    const { t, lang } = useTranslation();
//    <h1>{t('dashboard.title')}</h1>
// ─────────────────────────────────────────────────────────────

// ── Supported languages ───────────────────────────────────────
export const LANGUAGES = [
  { code: 'en', label: 'English',   nativeLabel: 'English',    flag: '🇬🇧', short: 'EN', rtl: false },
  { code: 'hi', label: 'Hindi',     nativeLabel: 'हिंदी',       flag: '🇮🇳', short: 'HI', rtl: false },
  { code: 'gu', label: 'Gujarati',  nativeLabel: 'ગુજરાતી',     flag: '🇮🇳', short: 'GU', rtl: false },
  { code: 'mr', label: 'Marathi',   nativeLabel: 'मराठी',       flag: '🇮🇳', short: 'MR', rtl: false },
  { code: 'ta', label: 'Tamil',     nativeLabel: 'தமிழ்',       flag: '🇮🇳', short: 'TA', rtl: false },
  { code: 'fr', label: 'French',    nativeLabel: 'Français',   flag: '🇫🇷', short: 'FR', rtl: false },
  { code: 'de', label: 'German',    nativeLabel: 'Deutsch',    flag: '🇩🇪', short: 'DE', rtl: false },
  { code: 'ar', label: 'Arabic',    nativeLabel: 'العربية',    flag: '🇸🇦', short: 'AR', rtl: true  },
];

// ── Master translation map ────────────────────────────────────
const translations = {
  en: {
    // ── Common ──
    'common.save':           'Save',
    'common.cancel':         'Cancel',
    'common.delete':         'Delete',
    'common.edit':           'Edit',
    'common.create':         'Create',
    'common.search':         'Search',
    'common.filter':         'Filter',
    'common.loading':        'Loading…',
    'common.no_data':        'No data found',
    'common.confirm':        'Confirm',
    'common.yes':            'Yes',
    'common.no':             'No',
    'common.status':         'Status',
    'common.actions':        'Actions',
    'common.view_all':       'View All',
    'common.close':          'Close',
    'common.submit':         'Submit',
    'common.approve':        'Approve',
    'common.reject':         'Reject',
    'common.pending':        'Pending',
    'common.approved':       'Approved',
    'common.rejected':       'Rejected',
    'common.active':         'Active',
    'common.inactive':       'Inactive',
    'common.name':           'Name',
    'common.email':          'Email',
    'common.phone':          'Phone',
    'common.date':           'Date',
    'common.from':           'From',
    'common.to':             'To',
    'common.description':    'Description',
    'common.type':           'Type',
    'common.role':           'Role',
    'common.department':     'Department',
    // ── Time ──
    'time.just_now':         'Just now',
    'time.min_ago':          'm ago',
    'time.hr_ago':           'h ago',
    'time.day_ago':          'd ago',
    // ── Nav / Layout ──
    'nav.dashboard':         'Dashboard',
    'nav.attendance':        'Attendance',
    'nav.leave':             'Leave',
    'nav.helpdesk':          'Helpdesk',
    'nav.announcements':     'Announcements',
    'nav.settings':          'Settings',
    'nav.policies':          'Policies',
    'nav.tasks_timesheet':   'Tasks & Timesheet',
    'nav.employees':         'Employees',
    'nav.hr_management':     'HR Management',
    'nav.wfh_records':       'WFH Records',
    'nav.payroll':           'Payroll',
    'nav.projects':          'Projects',
    'nav.assets':            'Assets',
    'nav.reports':           'Reports',
    'nav.inventory':         'Inventory',
    'nav.role_management':   'Role Management',
    'nav.audit_logs':        'Audit Logs',
    'nav.system_config':     'System Config',
    // ── Navbar ──
    'navbar.welcome':        'Welcome',
    'navbar.today_is':       'Today is',
    'navbar.notifications':  'Notifications',
    'navbar.mark_all_read':  'Mark all read',
    'navbar.no_notifications':'No notifications yet',
    'navbar.view_all':       'View all notifications',
    'navbar.my_profile':     'My Profile',
    'navbar.settings':       'Settings',
    'navbar.change_password':'Change Password',
    'navbar.logout':         'Logout',
    'navbar.dark_mode':      'Dark mode',
    'navbar.light_mode':     'Light mode',
    'navbar.language':       'Language',
    // ── Dashboard ──
    'dashboard.title':       'Dashboard',
    'dashboard.welcome':     'Welcome back',
    'dashboard.pending_approvals': 'Pending Approvals',
    'dashboard.system_health':     'System Health',
    'dashboard.approval_mode':     'Approval Mode',
    'dashboard.primary_mode':      'Primary Mode — Approvals Only',
    'dashboard.primary_mode_desc': 'You can view all data and approve/reject requests.',
    'dashboard.pending_policy':    'Pending Policy Approvals',
    'dashboard.system_config':     'System Config Requests',
    'dashboard.critical_ops':      'Critical Operations',
    // ── Attendance ──
    'attendance.title':      'Attendance',
    'attendance.mark':       'Mark Attendance',
    'attendance.check_in':   'Check In',
    'attendance.check_out':  'Check Out',
    'attendance.present':    'Present',
    'attendance.absent':     'Absent',
    'attendance.late':       'Late',
    'attendance.half_day':   'Half Day',
    'attendance.total_days': 'Total Days',
    'attendance.working_days':'Working Days',
    // ── Leave ──
    'leave.title':           'Leave Management',
    'leave.apply':           'Apply Leave',
    'leave.type':            'Leave Type',
    'leave.casual':          'Casual Leave',
    'leave.sick':            'Sick Leave',
    'leave.earned':          'Earned Leave',
    'leave.maternity':       'Maternity Leave',
    'leave.balance':         'Leave Balance',
    'leave.history':         'Leave History',
    'leave.reason':          'Reason',
    // ── Announcements ──
    'announcements.title':   'Announcements',
    'announcements.new':     'New Announcement',
    'announcements.visible_to': 'Visible to',
    'announcements.pinned':  'Pinned',
    'announcements.expires': 'Expires',
    'announcements.pin_top': 'Pin to top',
    // ── Employees ──
    'employees.title':       'Employees',
    'employees.add':         'Add Employee',
    'employees.position':    'Position',
    'employees.joined':      'Joined',
    'employees.salary':      'Salary',
    // ── Auth ──
    'auth.sign_in':          'Sign in to your account',
    'auth.sign_up':          'Create your account',
    'auth.forgot_password':  'Reset your password',
    'auth.email':            'Email address',
    'auth.password':         'Password',
    'auth.confirm_password': 'Confirm Password',
    'auth.username':         'Username',
    'auth.sign_in_btn':      'Sign in',
    'auth.sign_up_btn':      'Sign up',
    'auth.no_account':       "Don't have an account?",
    'auth.have_account':     'Already have an account?',
    'auth.reset_link':       'Send reset link',
    'auth.back_to_signin':   'Back to sign in',
    'auth.remember_pwd':     'Remember your password?',
    'auth.welcome_title':    'Welcome to Netpair Infotech',
    'auth.welcome_sub':      'Connecting your future with advanced HR management solutions.',
    'auth.join_title':       'Join Our Team',
    'auth.join_sub':         'Start your journey with our comprehensive HR management platform.',
    'auth.recover_title':    'Secure Recovery',
    'auth.recover_sub':      "We'll help you get back into your account safely.",
    // ── Helpdesk ──
    'helpdesk.title':        'Helpdesk',
    'helpdesk.new_ticket':   'New Ticket',
    'helpdesk.open':         'Open',
    'helpdesk.closed':       'Closed',
    'helpdesk.priority':     'Priority',
    'helpdesk.high':         'High',
    'helpdesk.medium':       'Medium',
    'helpdesk.low':          'Low',
    // ── Settings ──
    'settings.title':        'Settings',
    'settings.profile':      'Profile Settings',
    'settings.security':     'Security',
    'settings.notifications':'Notification Preferences',
    'settings.appearance':   'Appearance',
    'settings.language':     'Language & Region',
    // ── Payroll ──
    'payroll.title':         'Payroll',
    'payroll.generate':      'Generate Payslip',
    'payroll.basic':         'Basic Salary',
    'payroll.allowances':    'Allowances',
    'payroll.deductions':    'Deductions',
    'payroll.net':           'Net Salary',
    // ── System ──
    'system.healthy':        'Healthy',
    'system.operational':    'Operational',
    'system.active':         'Active',
    'system.degraded':       'Degraded',
    'system.down':           'Down',
    'system.database':       'Database',
    'system.email':          'Email Service',
    'system.auth':           'Auth Service',
    'system.socket':         'Socket.IO',
  },

  hi: {
    'common.save':           'सहेजें',
    'common.cancel':         'रद्द करें',
    'common.delete':         'हटाएं',
    'common.edit':           'संपादित करें',
    'common.create':         'बनाएं',
    'common.search':         'खोजें',
    'common.filter':         'फ़िल्टर',
    'common.loading':        'लोड हो रहा है…',
    'common.no_data':        'कोई डेटा नहीं',
    'common.confirm':        'पुष्टि करें',
    'common.yes':            'हाँ',
    'common.no':             'नहीं',
    'common.status':         'स्थिति',
    'common.actions':        'कार्यवाही',
    'common.view_all':       'सभी देखें',
    'common.close':          'बंद करें',
    'common.submit':         'जमा करें',
    'common.approve':        'स्वीकृत',
    'common.reject':         'अस्वीकृत',
    'common.pending':        'विचाराधीन',
    'common.approved':       'स्वीकृत',
    'common.rejected':       'अस्वीकृत',
    'common.active':         'सक्रिय',
    'common.inactive':       'निष्क्रिय',
    'common.name':           'नाम',
    'common.email':          'ईमेल',
    'common.phone':          'फ़ोन',
    'common.date':           'तारीख',
    'common.from':           'से',
    'common.to':             'तक',
    'common.description':    'विवरण',
    'common.type':           'प्रकार',
    'common.role':           'भूमिका',
    'common.department':     'विभाग',
    'time.just_now':         'अभी',
    'time.min_ago':          'मि. पहले',
    'time.hr_ago':           'घं. पहले',
    'time.day_ago':          'दि. पहले',
    'nav.dashboard':         'डैशबोर्ड',
    'nav.attendance':        'उपस्थिति',
    'nav.leave':             'छुट्टी',
    'nav.helpdesk':          'हेल्पडेस्क',
    'nav.announcements':     'घोषणाएं',
    'nav.settings':          'सेटिंग्स',
    'nav.policies':          'नीतियां',
    'nav.tasks_timesheet':   'कार्य और टाइमशीट',
    'nav.employees':         'कर्मचारी',
    'nav.hr_management':     'एचआर प्रबंधन',
    'nav.wfh_records':       'WFH रिकॉर्ड',
    'nav.payroll':           'वेतन',
    'nav.projects':          'परियोजनाएं',
    'nav.assets':            'संपत्ति',
    'nav.reports':           'रिपोर्ट',
    'nav.inventory':         'सूची',
    'nav.role_management':   'भूमिका प्रबंधन',
    'nav.audit_logs':        'ऑडिट लॉग',
    'nav.system_config':     'सिस्टम कॉन्फ़िग',
    'navbar.welcome':        'स्वागत है',
    'navbar.today_is':       'आज है',
    'navbar.notifications':  'सूचनाएं',
    'navbar.mark_all_read':  'सभी पढ़े',
    'navbar.no_notifications':'कोई सूचना नहीं',
    'navbar.view_all':       'सभी देखें',
    'navbar.my_profile':     'मेरी प्रोफ़ाइल',
    'navbar.settings':       'सेटिंग्स',
    'navbar.change_password':'पासवर्ड बदलें',
    'navbar.logout':         'लॉगआउट',
    'navbar.dark_mode':      'डार्क मोड',
    'navbar.light_mode':     'लाइट मोड',
    'navbar.language':       'भाषा',
    'dashboard.title':       'डैशबोर्ड',
    'dashboard.welcome':     'वापसी पर स्वागत',
    'dashboard.pending_approvals':'लंबित अनुमोदन',
    'dashboard.system_health':   'सिस्टम स्वास्थ्य',
    'dashboard.approval_mode':   'अनुमोदन मोड',
    'dashboard.primary_mode':    'प्राथमिक मोड — केवल अनुमोदन',
    'dashboard.primary_mode_desc':'आप सभी डेटा देख सकते हैं और अनुरोध स्वीकृत/अस्वीकार कर सकते हैं।',
    'attendance.title':      'उपस्थिति',
    'attendance.mark':       'उपस्थिति दर्ज करें',
    'attendance.check_in':   'चेक इन',
    'attendance.check_out':  'चेक आउट',
    'attendance.present':    'उपस्थित',
    'attendance.absent':     'अनुपस्थित',
    'leave.title':           'छुट्टी प्रबंधन',
    'leave.apply':           'छुट्टी के लिए आवेदन',
    'leave.reason':          'कारण',
    'leave.balance':         'छुट्टी शेष',
    'announcements.title':   'घोषणाएं',
    'announcements.new':     'नई घोषणा',
    'auth.sign_in':          'अपने खाते में साइन इन करें',
    'auth.sign_up':          'अपना खाता बनाएं',
    'auth.email':            'ईमेल पता',
    'auth.password':         'पासवर्ड',
    'auth.sign_in_btn':      'साइन इन',
    'auth.sign_up_btn':      'साइन अप',
    'auth.no_account':       'खाता नहीं है?',
    'auth.have_account':     'पहले से खाता है?',
    'auth.welcome_title':    'नेटपेयर इन्फोटेक में आपका स्वागत है',
    'auth.welcome_sub':      'उन्नत एचआर प्रबंधन समाधानों के साथ आपका भविष्य जोड़ना।',
    'system.healthy':        'स्वस्थ',
    'system.operational':    'सक्रिय',
    'system.active':         'चालू',
  },

  gu: {
    'common.save':           'સાચવો',
    'common.cancel':         'રદ કરો',
    'common.delete':         'કાઢી નાંખો',
    'common.edit':           'સંપાદિત કરો',
    'common.create':         'બનાવો',
    'common.search':         'શોધો',
    'common.filter':         'ફિલ્ટર',
    'common.loading':        'લોડ થઈ રહ્યું છે…',
    'common.no_data':        'કોઈ ડેટા નથી',
    'common.approve':        'મંજૂર',
    'common.reject':         'નામંજૂર',
    'common.pending':        'બાકી',
    'common.approved':       'મંજૂર',
    'common.rejected':       'નામંજૂર',
    'common.view_all':       'બધું જુઓ',
    'common.submit':         'સબમિટ',
    'time.just_now':         'હમણાં',
    'time.min_ago':          'મિ. પહેલા',
    'time.hr_ago':           'ક. પહેલા',
    'time.day_ago':          'દિ. પહેલા',
    'nav.dashboard':         'ડેશબોર્ડ',
    'nav.attendance':        'હાજરી',
    'nav.leave':             'રજા',
    'nav.helpdesk':          'હેલ્પડેસ્ક',
    'nav.announcements':     'જાહેરાતો',
    'nav.settings':          'સેટિંગ્સ',
    'nav.policies':          'નીતિઓ',
    'nav.tasks_timesheet':   'કાર્ય અને ટાઇમશીટ',
    'nav.employees':         'કર્મચારીઓ',
    'nav.hr_management':     'HR વ્યવસ્થાપન',
    'nav.wfh_records':       'WFH રેકોર્ડ',
    'nav.payroll':           'પગાર',
    'nav.projects':          'પ્રોજેક્ટ',
    'nav.assets':            'સંપત્તિ',
    'nav.reports':           'અહેવાલ',
    'nav.inventory':         'ઈન્વેન્ટરી',
    'nav.role_management':   'ભૂમિકા વ્યવસ્થાપન',
    'nav.audit_logs':        'ઓડિટ લૉગ',
    'nav.system_config':     'સિસ્ટમ કૉન્ફિગ',
    'navbar.welcome':        'સ્વાગત છે',
    'navbar.today_is':       'આજ છે',
    'navbar.notifications':  'સૂચનાઓ',
    'navbar.mark_all_read':  'બધું વાંચ્યું',
    'navbar.no_notifications':'કોઈ સૂચના નથી',
    'navbar.view_all':       'બધી જુઓ',
    'navbar.my_profile':     'મારી પ્રોફાઇલ',
    'navbar.settings':       'સેટિંગ્સ',
    'navbar.change_password':'પાસવર્ડ બદલો',
    'navbar.logout':         'લૉગઆઉટ',
    'navbar.dark_mode':      'ડાર્ક મોડ',
    'navbar.light_mode':     'લાઇટ મોડ',
    'navbar.language':       'ભાષા',
    'dashboard.title':       'ડેશબોર્ડ',
    'dashboard.pending_approvals':'બાકી મંજૂરી',
    'dashboard.system_health':   'સિસ્ટમ સ્વાસ્થ્ય',
    'dashboard.approval_mode':   'મંજૂરી મોડ',
    'auth.sign_in':          'તમારા એકાઉન્ટમાં સાઇન ઇન કરો',
    'auth.sign_up':          'તમારું એકાઉન્ટ બનાવો',
    'auth.email':            'ઈ-મેઇલ સરનામું',
    'auth.password':         'પાસવર્ડ',
    'auth.sign_in_btn':      'સાઇન ઇન',
    'auth.sign_up_btn':      'સાઇન અપ',
    'auth.no_account':       'એકાઉન્ટ નથી?',
    'auth.have_account':     'પહેલેથી એકાઉન્ટ છે?',
    'auth.welcome_title':    'નેટ્પેર ઈન્ફોટેકમાં આપનું સ્વાગત છે',
    'auth.welcome_sub':      'અદ્યતન HR સંચાલન ઉકેલો સાથે તમારા ભવિષ્ય સાથે જોડો.',
    'system.healthy':        'સ્વસ્થ',
    'system.operational':    'કાર્યશીલ',
    'system.active':         'સક્રિય',
  },
};

// ── Fallback chain: requested lang → en ──────────────────────
const translate = (lang, key) =>
  translations[lang]?.[key] ?? translations.en[key] ?? key;

export const timeAgo = (dateStr, lang = 'en') => {
  const diff = Math.floor((Date.now() - new Date(dateStr)) / 1000);
  if (diff < 60)    return translate(lang, 'time.just_now');
  if (diff < 3600)  return `${Math.floor(diff / 60)} ${translate(lang, 'time.min_ago')}`;
  if (diff < 86400) return `${Math.floor(diff / 3600)} ${translate(lang, 'time.hr_ago')}`;
  return `${Math.floor(diff / 86400)} ${translate(lang, 'time.day_ago')}`;
};

export { LANGUAGES, translate as t };
export default translate;
